services:
  postgres:
    image: postgres:15-alpine
    container_name: kai-postgres
    environment:
      POSTGRES_DB: kai
      POSTGRES_USER: kai_user
      POSTGRES_PASSWORD: kai_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kai_user -d kai"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: