spring:
  application:
    name: kai
  
  datasource:
    url: jdbc:postgresql://localhost:5432/kai
    username: kai_user
    password: kai_pass
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: never

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    
server:
  port: 8080
  
logging:
  level:
    org.hibernate: INFO
    org.springframework: INFO
    org.shark.kai: DEBUG